# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Kuan-Hao Chao"
title_separator          : "-"
name                     : &name "Kuan-Hao Chao"
description              : &description "CS Ph.D. student @ Center for Computational Biology, JHU, US<br><br>"
url                      : https://archive.khchao.com
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "kuanhao-chao.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles


# Analytics
analytics:
  provider               :  "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :

# News
newslist:

  - {time: "July, 2023", story: "Thrilled to release Splam v1.0.2, a splice site predictor that enhances spliced alignments. Check out the Splam <a href='https://github.com/Kuanhao-Chao/splam' target='_blank'>GitHub</a>, <a href='https://doi.org/10.1101/2023.07.27.550754' target='_blank'>preprint</a>, and the <a href='http://ccb.jhu.edu/splam/' target='_blank'>documentation</a>!"}

  - {time: "June, 2023", story: "My co-first author  paper on analyzing protein interactome using co-elution data is published in <i>Briefing in Bioinformatics</i>. Great collaboration with  <a href='https://bits.iis.sinica.edu.tw/' target='_blank'>HK Tsai Lab</a> and <a href='http://www.imb.sinica.edu.tw/~jleu/' target='_blank'>Jun-Yi Leu Lab</a>! See the paper <a href='https://doi.org/10.1093/bib/bbad229' target='_blank'>here</a>."}

  - {time: "May, 2023", story: "Splam is accepted as a poster at <a href='http://cosi.iscb.org/wiki/MLCSB:Home' target='_blank'>MLCSB COSI</a>, and <a href='https://doi.org/10.1093/g3journal/jkac321' target='_blank'>Han1</a> is accepted as a highlight poster at <a href='http://hitseq.org/' target='_blank'>HiTSeq COSI</a>. Exciting to share our work at <a href='https://www.iscb.org/ismbeccb2023' target='_blank'>ISMB/ECCB 2023</a> in Lyon, France."}

  - {time: "March, 2023", story: "My paper <a href='https://doi.org/10.1101/2022.10.15.512390' target='_blank'>WGT</a> is accepted to <a href='https://recomb-seq.github.io/' target='_blank'>RECOMB-Seq</a> as a proceedings track paper and <a href='http://recomb2023.bilkent.edu.tr/' target='_blank'>RECOMB</a> as a poster. Great collaboration with <a href='https://langmead-lab.org/' target='_blank'>langmead lab</a> and <a href='http://people.eecs.berkeley.edu/~sseshia/' target='_blank'>Seshia lab</a>. See you in İstanbul, Türkiye." }

  - {time: "Jan, 2023", story: "My paper in <i>G3: Genes, Genomes, Genetics</i> describes the first gap-free assembly of a <a href='https://www.ncbi.nlm.nih.gov/assembly/GCA_024586135.1/' target='_blank'>Han Chinese human, Han1</a>. See the paper <a href='https://doi.org/10.1093/g3journal/jkac321' target='_blank'>here</a>." }

  - {time: "Nov, 2022", story: "I present Han1 at <a href='https://meetings.cshl.edu/meetings.aspx?meet=data&year=22' target='_blank'>2022 Biological Data Science</a>! Here is the link to the <a href='https://storage.googleapis.com/storage.khchao.com/JHU%20PhD/Han1/Han1_poster.pdf' target='_blank'>poster</a> and the video to my <a href='https://youtu.be/2m5wrqqsn4E' target='_blank'>1-min lightening talk</a>." }

  - {time: "Oct, 2022", story: "We are releasing <a href='https://github.com/Kuanhao-Chao/Wheeler_Graph_Toolkit' target='_blank'>WGT</a>, the first Wheeler Graph suite with the fastest recognition algorithm. It's on <a href='https://doi.org/10.1101/2022.10.15.512390' target='_blank'>bioRxiv</a> now!" }

  - {time: "Aug, 2022", story: "We are releasing <a href='https://www.ncbi.nlm.nih.gov/assembly/GCA_024586135.1/' target='_blank'>Han1</a>, the first gapless, fully annotated Chinese Han genome. Check it out on <a href='https://doi.org/10.1101/2022.08.08.503226' target='_blank'>bioRxiv</a>!" }

  # - {time: "Dec, 2021", story: "<a href='http://140.112.136.49:8005/' target='_blank'>VaccineDynamic</a> website beta version is available online. Check it out!" }

  - {time: "Oct, 2021", story: "<a href='https://bioconductor.org/packages/release/bioc/html/sangeranalyseR.html' target='_blank'>sangeranalyseR</a> and <a href='https://www.bioconductor.org/packages/release/bioc/html/RNASeqR.html' target='_blank'>RNASeqR</a> are released on <i>Bioconductor 3.14</i>." }

  - {time: "Sep, 2021", story: "I join Dr. Steven Salzberg's and Dr. Mihaela Pertea's lab as a CS Ph.D. student at JHU." }

  - {time: "Aug, 2021", story: "sangeranalyseR is awarded the <strong>Best Poster</strong> at <a href='https://bioc2021.bioconductor.org/' target='_blank'>Bioc2021</a> <a href='https://f1000research.com/posters/10-888' target='_blank'> >>Poster<< </a>." }

  - {time: "June, 2021", story: "Play my <a href='https://khchao.com/projects/' target='_blank'>Unity games</a>!" }

  - {time: "Mar, 2021", story: "sangeranalyseR is published on <i><a href='https://doi.org/10.1093/gbe/evab028' target='_blank'>Genome Biology and Evolution</a></i>." }


# Site Author
author:
  name             : "Kuan-Hao Chao"
  avatar           : "profile.png"
  bio              : "Sr. Deep Learning Scientist, Illumina<br><br>"
  location         : "Taipei, Taiwan"
  employer         :
  googlescholar    : "https://scholar.google.com/citations?user=n2AvFg0AAAAJ&hl=en&oi=ao"
  email            : kuanhao.chao@gmail.com
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "Kuanhao-Chao"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "kuan-hao-chao"
  orcid            : "https://orcid.org/0000-0003-0099-0692"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : "KuanHaoChao"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - bin
  - config
  - vite.config.ts
  - tmp
  - Procfile.dev
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  about-us:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  # references:
  #   output: true
  #   permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  researches:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  presentations:
    output: true
    permalink: /:collection/:path/
  internship:
    output: true
    permalink: /:collection/:path/
  # games:
  #   output: true
  #   permalink: /:collection/:path/
  # projects:
  #   output: true
  #   permalink: /:collection/:path/
  photos:
    output: true
    permalink: /:collection/:path/
  contact:
    output: true
    permalink: /:collection/:path/
  news:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _about-us
  - scope:
      path: ""
      type: about-us
    values:
      layout: about-us
      author_profile: false
      share: true
      comments: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: teaching
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: portfolio
      author_profile: true
      share: true
      comment: true
  # _presentations
  - scope:
      path: ""
      type: presentations
    values:
      layout: presentation
      author_profile: true
      share: true
  # _researches
  - scope:
      path: ""
      type: researches
    values:
      layout: research
      author_profile: true
      share: true
      comments: true
  # _internship
  - scope:
      path: ""
      type: internship
    values:
      layout: internship
      author_profile: true
      share: true
  # - scope:
  #     path: ""
  #     type: projects
  #   values:
  #     layout: project
  #     author_profile: true
  #     share: true
  - scope:
      path: ""
      type: photos
    values:
      layout: photo
  - scope:
      path: ""
      type: contact
    values:
      layout: contact
  # - scope:
  #     path: ""
  #     type: references
  #   values:
  #     layout: reference
  #     author_profile: true
  #     share: true
  #     comments: true
  - scope:
      path: ""
      type: news
    values:
      layout: news
      author_profile: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll/vite
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
